#################
## DEVELOPMENT ##
#################
services:
  gateway-service:
    build:
      context: ./gateway-service
      target: development
    container_name: gateway-service
    command: npm run start:dev
    env_file:
      - ./gateway-service/.env
    ports:
      - "4000:4000"
    volumes:
      - ./gateway-service:/app
      - /app/node_modules
    depends_on:
      - question-service
      - user-service
      - auth-service
      - matching-service
      - collaboration-service
      # - eventstore.db
      - redis
    networks:
      - backend-network
      - shared-network

  question-service:
    build:
      context: ./question-service
      target: development
    container_name: question-service
    volumes:
      - ./question-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./question-service/.env
    networks:
      - backend-network
    ports:
      - "3002:4000"

  user-service:
    build:
      context: ./user-service
      target: development
    container_name: user-service
    command: npm run start:dev
    volumes:
      - ./user-service:/app
      - /app/node_modules
    env_file:
      - ./user-service/.env
    networks:
      - backend-network
    ports:
      - "3001:4000"

  auth-service:
    build:
      context: ./auth-service
      target: development
    container_name: auth-service
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./auth-service/.env
    networks:
      - backend-network
    ports:
      - "3003:4000"

  matching-service:
    build:
      context: ./matching-service
      target: development
    container_name: matching-service
    volumes:
      - ./matching-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./matching-service/.env
    networks:
      - backend-network
    ports:
      - "3004:4000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network

  collaboration-service:
    build:
      context: ./collaboration-service
      target: development
    container_name: collaboration-service
    volumes:
      - ./collaboration-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./collaboration-service/.env
    networks:
      - backend-network
    ports:
      - "3005:4000"

  y-websocket-service:
    build:
      context: ./y-websocket-service
      target: development
    container_name: y-websocket-service
    volumes:
      - ./y-websocket-service:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - "4001:4001"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
  shared-network:
    driver: bridge
