#################
## DEVELOPMENT ##
#################
services:
  gateway-service:
    build:
      context: ./gateway-service
      target: development
    container_name: gateway-service
    command: npm run start:dev
    env_file:
      - ./gateway-service/.env
    ports:
      - "4000:4000"
    volumes:
      - ./gateway-service:/app
      - /app/node_modules
    depends_on:
      - question-service
      - user-service
      - auth-service
      - matching-service
      - collaboration-service
      - eventstore.db
      - redis
    networks:
      - backend-network
      - shared-network

  question-service:
    build:
      context: ./question-service
      target: development
    container_name: question-service
    volumes:
      - ./question-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./question-service/.env
    networks:
      - backend-network
    ports:
      - "3002:4000"

  user-service:
    build:
      context: ./user-service
      target: development
    container_name: user-service
    command: npm run start:dev
    volumes:
      - ./user-service:/app
      - /app/node_modules
    env_file:
      - ./user-service/.env
    networks:
      - backend-network
    ports:
      - "3001:4000"

  auth-service:
    build:
      context: ./auth-service
      target: development
    container_name: auth-service
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./auth-service/.env
    networks:
      - backend-network
    ports:
      - "3003:4000"

  matching-service:
    build:
      context: ./matching-service
      target: development
    container_name: matching-service
    volumes:
      - ./matching-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./matching-service/.env
    networks:
      - backend-network
    ports:
      - "3004:4000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network

  collaboration-service:
    build:
      context: ./collaboration-service
      target: development
    container_name: collaboration-service
    volumes:
      - ./collaboration-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./collaboration-service/.env
    networks:
      - backend-network
    ports:
      - "3005:4000"

  eventstore.db:
    image: eventstore/eventstore:22.10.3-alpha-arm64v8 # For Apple M Chips
    # image: eventstore/eventstore:21.6.0-buster-slim # For ARM Chips
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DISABLE_INTERNAL_TCP_TLS=true
      - EVENTSTORE_DISABLE_EXTERNAL_TCP_TLS=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /c/data/eventstore/data
      - type: volume
        source: eventstore-volume-logs
        target: /c/data/eventstore/logs
    networks:
      - backend-network
    
    

networks:
  backend-network:
    driver: bridge
  shared-network:
    driver: bridge

volumes:
  eventstore-volume-data: {}
  eventstore-volume-logs: {}