apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: peerprep
  labels:
    app: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service
          image: asia-southeast1-docker.pkg.dev/peerprep-438213/peerprep/question-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: peerprep-secrets
            - configMapRef:
                name: question-configmap
      restartPolicy: Always
